# DATASET
DATASET_PATH: '../data'
CLASS_COLUMN_NAME: 'article_class'
ARTICLE_CONTENTS_COLUMN_NAME: 'contents'
BERT_MODEL: 'bert-base-cased'
TRAIN_NAME: 'aml_train'
VAL_NAME: 'aml_val'
NUM_WORKERS: 8
CLASS_MAPPING:
  no_aml: 0
  aml_aac: 1
  aml_cs: 2

# MODEL
BERT_MODEL_OUTPUT_SIZE: 768
AGGREGATING_NETWORK_OUTPUT_SIZE: 100
LEARNING_RATE: 1e-3
FEATURE_EXTRACTOR_WEIGHT_DECAY: 0
AGGREGATING_NETWORK_WEIGHT_DECAY: 1e-4
PREDICTOR_WEIGHT_DECAY: 5e-4
DROPOUT_RATE: 0.5
OPTIMIZER: 'Adam'