# DATASET
DATASET_PATH: '../data'
CLASS_COLUMN_NAME: 'Category'
ARTICLE_CONTENTS_COLUMN_NAME: 'Text'
BERT_MODEL: 'bert-base-cased'
TRAIN_NAME: 'bbc_train'
VAL_NAME: 'bbc_val'
NUM_WORKERS: 8
CLASS_MAPPING:
  business: 0
  tech: 1
  politics: 2
  sport: 3
  entertainment: 4

# MODEL
BERT_MODEL_OUTPUT_SIZE: 768
AGGREGATING_NETWORK_OUTPUT_SIZE: 100
LEARNING_RATE: 2e-5
FEATURE_EXTRACTOR_WEIGHT_DECAY: 0
AGGREGATING_NETWORK_WEIGHT_DECAY: 1e-6
PREDICTOR_WEIGHT_DECAY: 5e-6
DROPOUT_RATE: 0.5
OPTIMIZER: 'AdamW'  # ['Adam', 'SGD', 'AdamW']