BERT_MODEL: 'bert-base-cased'
BERT_MODEL_OUTPUT_SIZE: 768
AGGREGATING_NETWORK_OUTPUT_SIZE: 100
LEARNING_RATE: 1e-4
FEATURE_EXTRACTOR_WEIGHT_DECAY: 0
AGGREGATING_NETWORK_WEIGHT_DECAY: 1e-4
PREDICTOR_WEIGHT_DECAY: 5e-4
OUTPUT_MAPPING:
  0: 'Not AML related' 
  1: 'AML related - accusations / allegations / charges'
  2: 'AML related - convictions / sentences'